<div class="row">
    <div class="col-md-3">

        <!-- Profile Image -->
        <div class="box box-primary">
            <div class="box-body box-profile">
                <img class="profile-user-img img-responsive img-circle profilePicture" src="<?= ($this->image) ? $this->image : '/dist/img/user2-160x160.jpg' ?>" alt="User profile picture">

                <h3 class="profile-username text-center"><?= Zend_Auth::getInstance()->getIdentity()->name ?></h3>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Zapisanych CV</b> <a class="pull-right"><?= $this->countCv ?></a>
                    </li>
                    <li class="list-group-item">
                        <b>Zapisanych wykrztałceń</b> <a class="pull-right"> <?= $this->countEducation ?> </a>
                    </li>
                    <li class="list-group-item">
                        <b>Zapisanych miejsc pracy</b> <a class="pull-right"><?= $this->countWorkplace ?></a>
                    </li>
                    <li class="list-group-item">
                        <b>Zapisanych dodatkowych umiejętności</b> <a class="pull-right"><?= $this->countAdditionalSkills ?></a>
                    </li>
                    <li class="list-group-item">
                        <b>Zapisanych języków</b> <a class="pull-right"><?= $this->countLanguages ?></a>
                    </li>
                    <li class="list-group-item">
                        <b>Zapisanych linków</b> <a class="pull-right">-</a>
                    </li>
                </ul>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->

    </div>
    <!-- /.col -->
    <div class="col-md-9">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#personal-data" data-toggle="tab">Podstawowe dane</a></li>
                <li><a href="#change-password" data-toggle="tab">Zmiana hasła</a></li>
                <li><a href="#profile-picture" data-toggle="tab">Zdjęcie profilowe</a></li>
            </ul>
            <div class="tab-content">
                <div class="active tab-pane" id="personal-data">

                    <div class="box-body">
                        <form id="prifilePersonalDataForm" action="/profile/save">
                            <!-- text input -->
                            <div class="form-group">
                                <label>E-mail</label>
                                <input type="email" name="mail" value="<?= $this->mail ?>" disabled class="form-control" placeholder="Adres e-mail">
                            </div>
                            <div class="form-group">
                                <label>Imie</label>
                                <input type="text" name="firstName" value="<?= $this->firstname ?>" class="form-control" placeholder="Imię">
                            </div>
                            <div class="form-group">
                                <label>Nazwisko</label>
                                <input type="text" name="lastName" value="<?= $this->lastname ?>" class="form-control" placeholder="Nazwisko">
                            </div>
                            <div class="form-group">
                                <label>Numer telefonu</label>
                                <input type="text" name="phone" value="<?= $this->phone ?>" class="form-control" placeholder="Numer telefonu">
                            </div>
                            <div class="form-group">
                                <label>Stan cywilny</label>
                                <input type="text" name="maritalStatus" value="<?= $this->maritalstatus ?>" class="form-control" placeholder="Stan cywilny">
                            </div>
                            <div class="form-group">
                                <label>Data urodzenia</label>
                                <input type="text" name="birthDate" value="<?= $this->birthdate ?>" class="form-control" id="datepicker_birthdate" placeholder="Data urodzenia">
                            </div>
                            <div class="form-group">
                                <label>Miejsce urodzenia</label>
                                <input type="text" name="birthPlace" value="<?= $this->birthplace ?>" class="form-control" placeholder="Miejsce urodzenia">
                            </div>
                            <div class="form-group">
                                <label>Adres ulica, nr domu</label>
                                <input type="text" name="addressStreet" value="<?= $this->addressstreet ?>" class="form-control" placeholder="Ulica">
                            </div>
                            <div class="form-group">
                                <label>Adres poczta</label>
                                <input type="text" name="addressPost" value="<?= $this->addresspost ?>" class="form-control" placeholder="Kod pocztowy, poczta">
                            </div>
                            <div class="box-footer">
                                <div class="btn btn-info pull-right formSubmit">Zapisz</div>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->

                </div>
                <!-- /.tab-pane -->
                <div class="tab-pane" id="change-password">

                    <!-- /.box-header -->
                    <div class="box-body">
                        <form id="prifileChangePasswordForm" action="/profile/change-password">
                            <!-- text input -->
                            <div class="form-group">
                                <label>Aktualne hasło</label>
                                <input type="password" name="passwordActual" class="form-control" placeholder="Aktualne hasło">
                            </div>
                            <div class="form-group">
                                <label>Nowe hasło</label>
                                <input type="password" name="password" class="form-control" placeholder="Nowe hasło">
                            </div>
                            <div class="form-group">
                                <label>Nowe hasło ponownie</label>
                                <input type="password" name="passwordAgain" class="form-control" placeholder="Nowe hasło ponownie">
                            </div>
                            <div class="box-footer">
                                <div class="btn btn-info pull-right formSubmit">Zapisz</div>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->

                </div>
                <div class="tab-pane" id="profile-picture">


                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" id="profilePictureForm">
                        <div class="box-body">
                            <div class="form-group">
                                <label for="exampleInputFile">Wbierz zdjęcie które będzie wykorzystywane do CV</label>
                                <input name="file" type="file" id="exampleInputFile">
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <div id="profilePictureFormSubmit" class="btn btn-primary">Wgraj</div>
                        </div>
                    </form>

                </div>

                <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
        </div>
        <!-- /.nav-tabs-custom -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->

<script>
    $(document).ready(function () {
        $("#datepicker_birthdate").datepicker();
    });
</script>