<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tbody><tr>
                            <th>ID</th>
                            <th>Imie i nazwisko</th>
                            <th>Adres e-mail</th>
                            <th>Data rejestracji</th>
                            <th>Data ostatniego logowania</th>
                            <th>Rola systemowa</th>
                            <th>Status</th>
                            <th>Akcje</th>
                        </tr>
                        <?php foreach ($this->users as $user): ?>
                            <tr>
                                <td><?= $user['id'] ?></td>
                                <td><?= $user['name'] ?></td>
                                <td><?= $user['mail'] ?></td>
                                <td><?= $user['dateregister'] ?></td>
                                <td><?= $user['datelastlogon'] ?></td>
                                <td><?= $user['rolename'] ?></td>
                                <?php if ($user['status']): ?>
                                    <td><span class="label label-success">Aktywny</span></td>
                                <?php else: ?>
                                    <td><span class="label label-danger">Zablokowany</span></td>
                                <?php endif; ?>

                                <?php if (Zend_Auth::getInstance()->getIdentity()->id != $user['id']): ?>
                                    <?php if ($user['status']): ?>
                                        <td>
                                            <a href="" class="ajaxAction" data-action="/admin/user-deactivate" data-id="<?= $user['id'] ?>"><i class="fa fa-fw fa-remove" title="Dezaktywuj konto"></i></a>
                                        </td>
                                    <?php else: ?>
                                        <td>
                                            <a href="" class="ajaxAction" data-action="/admin/user-activate" data-id="<?= $user['id'] ?>"><i class="fa fa-fw fa-plus" title="Aktywuj konto"></i></a>
                                        </td>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <td></td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody></table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>