<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Dodaj nowe CV</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <form id="cvAddForm" action="/cv/save">


            <div class="form-group">
                <label>Nazwa CV</label>
                <input class="form-control" name="myName" placeholder="Moja nazwa"></input>
            </div>

            <div class="form-group">
                <label>Wybierz wygląd</label>
                <select name="layoutID" class="form-control">
                    <option value="1">Wygląd 1</option>
                </select>
            </div>

            <div class="form-group">
                <label>Zainteresowania</label>
                <textarea class="form-control" name="interests" rows="3" placeholder="zainteresowania po przecinku"></textarea>
            </div>

            <div class="box-footer">
                <div class="btn btn-info pull-right formSubmit">Zapisz</div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>