<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Dodaj nowe CV</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <form id="cvAddForm" action="/cv/save">


            <div class="form-group">
                <label>Zainteresowania</label>
                <textarea class="form-control" name="interests" rows="3" placeholder=""></textarea>
            </div>

            <div class="box-footer">
                <div class="btn btn-info pull-right formSubmit">Zapisz</div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>