<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Dodaj nowe CV</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <form id="cvAddForm" action="/cv/save">


            <div class="form-group">
                <label>Nazwa CV</label>
                <input class="form-control" name="name" placeholder="Moja nazwa"></input>
            </div>

            <div class="form-group">
                <label>Wybierz wygląd</label>
                <select name="layoutID" class="form-control">
                    <?php foreach (Application_Model_PdfLayout::getNamesArray() as $id => $name): ?>
                        <option value="<?= $id ?>"><?= $name ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <label>Zainteresowania</label>
                <textarea class="form-control" name="interests" rows="3" placeholder="zainteresowania po przecinku"></textarea>
            </div>

            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title">Wybierz wykrztałcenie które zostanie dołączone do tego CV</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <?php foreach ($this->education as $e): ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="education_<?= $e['id'] ?>">
                                    <?= sprintf('%s (%s - %s)', $e['description'], $e['date_of'], $e['date_to']) ?>
                                </label>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title">Wybierz miejsca pracy które zostaną dołączone do tego CV</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <?php foreach ($this->workplace as $e): ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="workplace_<?= $e['id'] ?>">
                                    <?= sprintf('%s (%s - %s)', $e['description'], $e['date_of'], $e['date_to']) ?>
                                </label>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title">Wybierz dodatkowe umiejętności które zostaną dołączone do tego CV</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <?php foreach ($this->additionalSkills as $e): ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="additionalSkills_<?= $e['id'] ?>">
                                    <?= sprintf('%s (%s)', $e['description'], $e['date']) ?>
                                </label>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title">Wybierz języki które zostaną dołączone do tego CV</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <?php foreach ($this->languages as $e): ?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="languages_<?= $e['id'] ?>">
                                    <?= sprintf('%s %s', $e['name'], $e['description']) ?>
                                </label>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="btn btn-info pull-right formSubmit">Zapisz</div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>

<script>
    $(document).ready(function () {


    });
</script>