<div class="box box-info">

    <div class="box-body">
        <form id="cvWorkplaceForm" action="/cv/add-additional-skills">
            <div class="form-group">
                <label>Nazwa umiejętności</label>
                <input type="text" name="description"  class="form-control" placeholder="">
            </div>
            <div class="form-group">
                <label>Data zdobycia umiejętności</label>
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" name="date" class="form-control pull-right" id="datepicker_date">
                </div>
            </div>
            <div class="box-footer">
                <div class="btn btn-info pull-right formSubmit">Dodaj</div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>

<script>
    $(document).ready(function () {
        $("#datepicker_date").datepicker();
    });
</script>