<div class="box box-info">

    <div class="box-body">
        <form id="cvWorkplaceForm" action="/cv/add-additional-skills">
            <div class="form-group">
                <label>Nazwa umiejętności</label>
                <input type="text" name="description"  class="form-control" placeholder="">
            </div>
            <div class="form-group">
                <label>Data zdobycia umiejętności</label>
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" name="date" class="form-control pull-right" id="datepicker_date">
                </div>
            </div>
            <div class="box-footer">
                <div class="btn btn-info pull-right formSubmit">Dodaj</div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>

<div class="box">
    <div class="box-body no-padding">
        <table class="table table-condensed">
            <tbody><tr>
                    <th style="width: 10px">#</th>
                    <th>Nazwa</th>
                    <th>Data</th>
                    <th>Akcje</th>
                </tr>
                <?php foreach ($this->additionalSkills as $k => $e): ?>
                    <tr>
                        <td><?= sprintf('%s.', $k + 1) ?></td>
                        <td><?= $e['description'] ?></td>
                        <td><?= $e['date'] ?></td>
                        <td>
                            <a href="" class="ajaxActionRemove" data-action="/cv/remove-additional-skills" data-id="<?= $e['id'] ?>"><i class="fa fa-fw fa-remove"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody></table>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->

<script>
    $(document).ready(function () {
        $("#datepicker_date").datepicker();
    });
</script>