<div class="box box-info">

    <div class="box-body">
        <form id="cvEducationForm" action="/cv/add-education">
            <div class="form-group">
                <label>Nazwa uczelni</label>
                <input type="text" name="description"  class="form-control" placeholder="">
            </div>
            <div class="form-group">
                <label>Rok rozpoczęcia</label>
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" name="date_of" class="form-control pull-right" id="datepicker_date_of">
                </div>
            </div>
            <div class="form-group">
                <label>Rok zakończenia</label>
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" name="date_to" class="form-control pull-right" id="datepicker_date_to">
                </div>
            </div>
            <div class="box-footer">
                <div class="btn btn-info pull-right formSubmit">Dodaj</div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>

<div class="box">
    <div class="box-body no-padding">
        <table class="table table-condensed">
            <tbody><tr>
                    <th style="width: 10px">#</th>
                    <th>Nazwa</th>
                    <th>Data rozpoczęcia</th>
                    <th>Data zakończenia</th>
                    <th>Akcje</th>
                </tr>
                <?php foreach ($this->education as $k => $e): ?>
                    <tr>
                        <td><?= sprintf('%s.', $k + 1) ?></td>
                        <td><?= $e['description'] ?></td>
                        <td><?= $e['date_of'] ?></td>
                        <td><?= $e['date_to'] ?></td>
                        <td>
                            <a href="" class="ajaxAction" data-action="/cv/remove-education" data-id="<?= $e['id'] ?>"><i class="fa fa-fw fa-remove"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody></table>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->
<script>
    $(document).ready(function () {
        $("#datepicker_date_of").datepicker();
        $("#datepicker_date_to").datepicker();
    });
</script>