<div class="box">
    <div class="box-body no-padding">
        <table class="table table-condensed">
            <tbody><tr>
                    <th style="width: 10px">#</th>
                    <th>Nazwa CV</th>
                    <th>Wygląd</th>
                    <th>PDF</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>Moje pierwsze CV</td>
                    <td>
                        Wygląd 1
                    </td>
                    <td>
                        <a href="/cv/pdf">
                            <i class="fa fa-fw fa-download"></i>
                        </a>
                    </td>
                </tr>
            </tbody></table>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->