<div class="box">
    <div class="box-body no-padding">
        <table class="table table-condensed">
            <tbody><tr>
                    <th style="width: 10px">#</th>
                    <th>Nazwa CV</th>
                    <th>Wygląd</th>
                    <th>Zainteresowania</th>
                    <th>PDF</th>
                </tr>
                <?php foreach ($this->cvs as $k => $cv): ?>
                    <tr>
                        <td><?= sprintf('%s.', $k + 1) ?></td>
                        <td><?= $cv['name'] ?></td>
                        <td><?= Application_Model_PdfLayout::convertIntToStringRepresentation($cv['pdf_layout']) ?></td>
                        <td><?= $cv['interests'] ?></td>
                        <td>
                            <a href="/cv/pdf/<?= $cv['id'] ?>">
                                <i class="fa fa-fw fa-download"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody></table>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->