<div class="box box-info">

    <div class="box-body">
        <form id="cvLanguagesForm" action="/cv/add-languages">
            <div class="form-group">
                <label>Nazwa języka</label>
                <input type="text" name="name"  class="form-control" placeholder="">
            </div>
            <div class="form-group">
                <label>Opis</label>
                <input type="text" name="description"  class="form-control" placeholder="">
            </div>
            <div class="box-footer">
                <div class="btn btn-info pull-right formSubmit">Dodaj</div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>

<div class="box">
    <div class="box-body no-padding">
        <table class="table table-condensed">
            <tbody><tr>
                    <th style="width: 10px">#</th>
                    <th>Nazwa</th>
                    <th>Opis</th>
                    <th>Akcje</th>
                </tr>
                <?php foreach ($this->languages as $k => $e): ?>
                    <tr>
                        <td><?= sprintf('%s.', $k + 1) ?></td>
                        <td><?= $e['name'] ?></td>
                        <td><?= $e['description'] ?></td>
                        <td>
                            <a href="" class="ajaxActionRemove" data-action="/cv/remove-languages" data-id="<?= $e['id'] ?>"><i class="fa fa-fw fa-remove"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody></table>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->