<div class="box box-info">

    <div class="box-body">
        <form id="cvLanguagesForm" action="/cv/add-workplace">
            <div class="form-group">
                <label>Nazwa języka</label>
                <input type="text" name="name"  class="form-control" placeholder="">
            </div>
            <div class="form-group">
                <label>Opis</label>
                <input type="text" name="description"  class="form-control" placeholder="">
            </div>
            <div class="box-footer">
                <div class="btn btn-info pull-right formSubmit">Dodaj</div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>