<div class="pdf">

    <div class="title">Curriculum Vitae</div>

    <div class="item-header">
        <div class="item-title">Łukasz Czekaj</div>
        <div class="hr"></div>
        <div class="div-table">
            <div class="div-table-row">
                <div class="div-table-col bold">Stan cywilny:</div>
                <div class="div-table-col">Kawaler</div>
            </div>
            <div class="div-table-row">
                <div class="div-table-col bold">Data urodzenia:</div>
                <div class="div-table-col">1 czerwiec 1991</div>
            </div>
            <div class="div-table-row">
                <div class="div-table-col bold">Miejsce urodzenia:</div>
                <div class="div-table-col">Kielce</div>
            </div>
            <div class="div-table-row">
                <div class="div-table-col bold">Adres:</div>
                <div class="div-table-col">
                    <span>Lechówek 47A</span>
                    <span>26-025 Łagów</span>
                </div>
            </div>
            <div class="div-table-row">
                <div class="div-table-col bold">Telefon:</div>
                <div class="div-table-col">874587344</div>
            </div>
            <div class="div-table-row">
                <div class="div-table-col bold">Email:</div>
                <div class="div-table-col">lukasz@lukaszczekaj.pl</div>
            </div>

        </div>
    </div>

    <div class="item">
        <div class="item-title">Wykrztałcenie</div>
        <div class="hr"></div>
        <div class="div-table">
            <div class="div-table-row">
                <div class="div-table-col">2011 - nadal</div>
                <div class="div-table-col-second">
                    Studia Inżynierskie na Politechnice Świętokrzyskiej w Kielcach, kierunek informatyka,
                </div>
            </div>
            <div class="div-table-row">
                <div class="div-table-col">2007 - 2011</div>
                <div class="div-table-col-second">
                    Zespół Szkół Informatycznych im. gen. Józefa Hauke Bosaka w Kielcach, tytuł technika informatyka.
                </div>
            </div>
        </div>
    </div>

    <div class="item">
        <div class="item-title">Doświadczenie zawodowe</div>
        <div class="hr"></div>
        <div class="div-table">
            <div class="div-table-row">
                <div class="div-table-col">07.2013</div>
                <div class="div-table-col-second">
                    Miesięczne praktyki zawodowe w firmie Complex Computers Sp. z o.o. w Kielcach,
                </div>
            </div>
            <div class="div-table-row">
                <div class="div-table-col">05.2012</div>
                <div class="div-table-col-second">
                    Uczestnictwo w kursie CCNA Exploration: Network Fundamentals,
                </div>
            </div>
            <div class="div-table-row">
                <div class="div-table-col">06.2009 – 10.2010</div>
                <div class="div-table-col-second">
                    Uczestnictwo w szkoleniu „Uczeń z międzynarodowym certyfikatem zawodowym- modelowe rozwiązanie dla świętokrzyskich pracodawców” realizowane przez COMBIDATA POLAND Sp. z o.o.,
                </div>
            </div>
        </div>
    </div>

    <div class="item">
        <div class="item-title">Języki</div>
        <div class="hr"></div>
        <div class="div-table-row">
            <div class="div-table-col listitem">
                j. angielski
            </div>
            <div class="div-table-col-second">
                - poziom średni w mowie i piśmie
            </div>
        </div>

    </div>

    <div class="item">
        <div class="item-title">Umiejętnośi</div>
        <div class="hr"></div>
        <ul>
            <li>szybkie nawiązywanie kontaktów, umiejętność współpracy w zespole</li>
            <li>bardzo dobra obsługa komputera, znajomość systemów operacyjnych Windows oraz urządzeń peryferyjnych komputera,</li>
            <li>bardzo dobra znajomość zagadnień związanych z sieciami komputerowymi,</li>
            <li>prawo jazdy kat. B.</li>
        </ul>
    </div>

    <div class="item">
        <div class="item-title">Zainteresowania</div>
        <div class="hr"></div>
        <ul>
            <li>muzyka, sport, elektronika</li>
        </ul>
    </div>

    <div class="footer">
        Wyrażam zgodę na przetwarzanie moich danych osobowych dla potrzeb niezbędnych do realizacji procesu rekrutacji (zgodnie z Ustawą z dnia 29.08.1997 roku o Ochronie Danych Osobowych; tekst jednolity: Dz. U. z 2002r. Nr 101, poz. 926 ze zm.)
    </div>

</div>