<div class="box box-info">

    <div class="box-body">
        <form id="cvWorkplaceForm" action="/cv/add-workplace">
            <div class="form-group">
                <label>Nazwa firmy</label>
                <input type="text" name="description"  class="form-control" placeholder="">
            </div>
            <div class="form-group">
                <label>Rok rozpoczęcia</label>
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" name="date_of" class="form-control pull-right" id="datepicker_date_of">
                </div>
            </div>
            <div class="form-group">
                <label>Rok zakończenia</label>
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" name="date_to" class="form-control pull-right" id="datepicker_date_to">
                </div>
            </div>
            <div class="box-footer">
                <div class="btn btn-info pull-right formSubmit">Dodaj</div>
            </div>
        </form>
    </div>
    <!-- /.box-body -->
</div>

<script>
    $(document).ready(function () {
        $("#datepicker_date_of").datepicker();
        $("#datepicker_date_to").datepicker();
    });
</script>